export interface ArabicLetter {
  id: string;
  arabic: string;
  name: string;
  nameHe: string;
  pronunciation: string;
  forms: {
    isolated: string;
    initial: string;
    medial: string;
    final: string;
  };
  strokeHint: string;
  connects: boolean;
}

export const ARABIC_LETTERS: ArabicLetter[] = [
  {
    id: "alef",
    arabic: "ا",
    name: "ألف",
    nameHe: "אלף",
    pronunciation: "a / ā",
    forms: {
      isolated: "ا",
      initial: "ا",
      medial: "ا",
      final: "ا",
    },
    strokeHint: "קו ישר אנכי מלמעלה למטה. האות אינה מתחברת משמאל.",
    connects: false,
  },
  {
    id: "ba",
    arabic: "ب",
    name: "باء",
    nameHe: "בּאא",
    pronunciation: "b",
    forms: {
      isolated: "ب",
      initial: "بـ",
      medial: "ـبـ",
      final: "ـب",
    },
    strokeHint: "קו אופקי עם קעירות קטנה למטה ונקודה אחת מתחת. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "ta",
    arabic: "ت",
    name: "تاء",
    nameHe: "תאא",
    pronunciation: "t",
    forms: {
      isolated: "ت",
      initial: "تـ",
      medial: "ـتـ",
      final: "ـت",
    },
    strokeHint: "זהה לבּאא אך עם שתי נקודות מעל. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "tha",
    arabic: "ث",
    name: "ثاء",
    nameHe: "ת׳אא",
    pronunciation: "th (כמו think)",
    forms: {
      isolated: "ث",
      initial: "ثـ",
      medial: "ـثـ",
      final: "ـث",
    },
    strokeHint: "זהה לבּאא אך עם שלוש נקודות מעל. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "jim",
    arabic: "ج",
    name: "جيم",
    nameHe: "ג׳ים",
    pronunciation: "j",
    forms: {
      isolated: "ج",
      initial: "جـ",
      medial: "ـجـ",
      final: "ـج",
    },
    strokeHint: "קשת עגולה עם זנב ונקודה אחת בתוך הקשת. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "ha",
    arabic: "ح",
    name: "حاء",
    nameHe: "חאא",
    pronunciation: "ḥ (ח גרונית)",
    forms: {
      isolated: "ح",
      initial: "حـ",
      medial: "ـحـ",
      final: "ـح",
    },
    strokeHint: "זהה לג׳ים אך ללא נקודה. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "kha",
    arabic: "خ",
    name: "خاء",
    nameHe: "ח׳אא",
    pronunciation: "kh (כמו לך בעברית)",
    forms: {
      isolated: "خ",
      initial: "خـ",
      medial: "ـخـ",
      final: "ـخ",
    },
    strokeHint: "זהה לחאא אך עם נקודה אחת מעל. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "dal",
    arabic: "د",
    name: "دال",
    nameHe: "דאל",
    pronunciation: "d",
    forms: {
      isolated: "د",
      initial: "د",
      medial: "ـد",
      final: "ـد",
    },
    strokeHint: "קו ישר עם עקומה קלה בתחתית ימינה. אינה מתחברת משמאל.",
    connects: false,
  },
  {
    id: "dhal",
    arabic: "ذ",
    name: "ذال",
    nameHe: "ד׳אל",
    pronunciation: "dh (כמו the באנגלית)",
    forms: {
      isolated: "ذ",
      initial: "ذ",
      medial: "ـذ",
      final: "ـذ",
    },
    strokeHint: "זהה לדאל אך עם נקודה אחת מעל. אינה מתחברת משמאל.",
    connects: false,
  },
  {
    id: "ra",
    arabic: "ر",
    name: "راء",
    nameHe: "ראא",
    pronunciation: "r",
    forms: {
      isolated: "ر",
      initial: "ر",
      medial: "ـر",
      final: "ـر",
    },
    strokeHint: "עקומה פשוטה כלפי מטה ושמאלה, כמו חצי עיגול. אינה מתחברת משמאל.",
    connects: false,
  },
  {
    id: "zay",
    arabic: "ز",
    name: "زاي",
    nameHe: "זאי",
    pronunciation: "z",
    forms: {
      isolated: "ز",
      initial: "ز",
      medial: "ـز",
      final: "ـز",
    },
    strokeHint: "זהה לראא אך עם נקודה אחת מעל. אינה מתחברת משמאל.",
    connects: false,
  },
  {
    id: "sin",
    arabic: "س",
    name: "سين",
    nameHe: "סין",
    pronunciation: "s",
    forms: {
      isolated: "س",
      initial: "سـ",
      medial: "ـسـ",
      final: "ـس",
    },
    strokeHint: "שלוש גלים קטנים ואז זנב ארוך שמאלה. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "shin",
    arabic: "ش",
    name: "شين",
    nameHe: "שין",
    pronunciation: "sh",
    forms: {
      isolated: "ش",
      initial: "شـ",
      medial: "ـشـ",
      final: "ـش",
    },
    strokeHint: "זהה לסין אך עם שלוש נקודות מעל. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "sad",
    arabic: "ص",
    name: "صاد",
    nameHe: "צאד",
    pronunciation: "ṣ (ס מודגשת)",
    forms: {
      isolated: "ص",
      initial: "صـ",
      medial: "ـصـ",
      final: "ـص",
    },
    strokeHint: "עיגול קטן עם זנב ארוך שמאלה. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "dad",
    arabic: "ض",
    name: "ضاد",
    nameHe: "צ׳אד",
    pronunciation: "ḍ (ד מודגשת)",
    forms: {
      isolated: "ض",
      initial: "ضـ",
      medial: "ـضـ",
      final: "ـض",
    },
    strokeHint: "זהה לצאד אך עם נקודה אחת מעל. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "ta2",
    arabic: "ط",
    name: "طاء",
    nameHe: "טאא",
    pronunciation: "ṭ (ט מודגשת)",
    forms: {
      isolated: "ط",
      initial: "طـ",
      medial: "ـطـ",
      final: "ـط",
    },
    strokeHint: "עיגול עם קו ישר אנכי בתוכו. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "dha2",
    arabic: "ظ",
    name: "ظاء",
    nameHe: "ד׳אא",
    pronunciation: "ẓ (ז מודגשת)",
    forms: {
      isolated: "ظ",
      initial: "ظـ",
      medial: "ـظـ",
      final: "ـظ",
    },
    strokeHint: "זהה לטאא אך עם נקודה אחת מעל. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "ain",
    arabic: "ع",
    name: "عين",
    nameHe: "עין",
    pronunciation: "ʿ (עין)",
    forms: {
      isolated: "ع",
      initial: "عـ",
      medial: "ـعـ",
      final: "ـع",
    },
    strokeHint: "עיגול פתוח בראשו עם זנב מאחור. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "ghain",
    arabic: "غ",
    name: "غين",
    nameHe: "ע׳ין",
    pronunciation: "gh (ר צרפתית)",
    forms: {
      isolated: "غ",
      initial: "غـ",
      medial: "ـغـ",
      final: "ـغ",
    },
    strokeHint: "זהה לעין אך עם נקודה אחת מעל. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "fa",
    arabic: "ف",
    name: "فاء",
    nameHe: "פאא",
    pronunciation: "f",
    forms: {
      isolated: "ف",
      initial: "فـ",
      medial: "ـفـ",
      final: "ـف",
    },
    strokeHint: "עיגול קטן עם קו ארוך ונקודה אחת מעל. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "qaf",
    arabic: "ق",
    name: "قاف",
    nameHe: "קאף",
    pronunciation: "q (כּ גרונית)",
    forms: {
      isolated: "ق",
      initial: "قـ",
      medial: "ـقـ",
      final: "ـق",
    },
    strokeHint: "עיגול עם שתי נקודות מעל וזנב כפול למטה. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "kaf",
    arabic: "ك",
    name: "كاف",
    nameHe: "כּאף",
    pronunciation: "k",
    forms: {
      isolated: "ك",
      initial: "كـ",
      medial: "ـكـ",
      final: "ـك",
    },
    strokeHint: "קשת עם קו אלכסוני קטן בתוכה. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "lam",
    arabic: "ل",
    name: "لام",
    nameHe: "לאם",
    pronunciation: "l",
    forms: {
      isolated: "ل",
      initial: "لـ",
      medial: "ـلـ",
      final: "ـل",
    },
    strokeHint: "קשת עגולה עם זנב ארוך לשמאל ומטה. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "mim",
    arabic: "م",
    name: "ميم",
    nameHe: "מים",
    pronunciation: "m",
    forms: {
      isolated: "م",
      initial: "مـ",
      medial: "ـمـ",
      final: "ـم",
    },
    strokeHint: "עיגול קטן סגור עם זנב קטן למטה. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "nun",
    arabic: "ن",
    name: "نون",
    nameHe: "נון",
    pronunciation: "n",
    forms: {
      isolated: "ن",
      initial: "نـ",
      medial: "ـنـ",
      final: "ـن",
    },
    strokeHint: "קשת קטנה עם נקודה אחת בתוכה. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "ha2",
    arabic: "ه",
    name: "هاء",
    nameHe: "הּאא",
    pronunciation: "h",
    forms: {
      isolated: "ه",
      initial: "هـ",
      medial: "ـهـ",
      final: "ـه",
    },
    strokeHint: "שני עיגולים קשורים זה לזה. מתחברת משני הצדדים.",
    connects: true,
  },
  {
    id: "waw",
    arabic: "و",
    name: "واو",
    nameHe: "ואו",
    pronunciation: "w / ū",
    forms: {
      isolated: "و",
      initial: "و",
      medial: "ـو",
      final: "ـو",
    },
    strokeHint: "עיגול קטן עם זנב קצר למטה. אינה מתחברת משמאל.",
    connects: false,
  },
  {
    id: "ya",
    arabic: "ي",
    name: "ياء",
    nameHe: "יאא",
    pronunciation: "y / ī",
    forms: {
      isolated: "ي",
      initial: "يـ",
      medial: "ـيـ",
      final: "ـي",
    },
    strokeHint: "קשת עם זנב ארוך ושתי נקודות מתחת. מתחברת משני הצדדים.",
    connects: true,
  },
];
